name: e2e test
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.png'
jobs:
  job_1:
    name: e2e test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.18.x, 1.19.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go build
        run: |
          go install .;
          gococo version
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
        run: |
          cd tests;
          pip install -r requirements.txt
      - name: run e2e test
        run: |
          cd tests && pytest